### ISSUE TITLE
Configure Github Actions for BDD test

### ISSUE THREAD

**Issue by aurelioym** [shopcarts-nyu/shopcart#34]
**As a** Developer
 **I need** my functions to go to the final test development stage 
 **So that** our stories are not accepted if they are failing 
   
 ### Details and Assumptions
 Integrations with Visual Code
Code

   
 ### Acceptance Criteria  
   
 ```gherkin
Given any function 
When is commited to the system
Then it is tested to see if it passes the Acceptance Criteria and can be used for integration

 ```

**Comment by hj2194** [comment]
moved to Product Backlog since we can't do this until finishing requirement #4
